apiVersion: v1
kind: Service
metadata:
  name: docker-react-node-port
spec:
  type: LoadBalancer
  selector:
    component: docker-react
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515
